#Sources
#https://cran.r-project.org/web/packages/mice/mice.pdf
#https://stefvanbuuren.name/mice/


require(tidyverse)
require(mice)
require(inspectdf)
library(lattice)
seed(123)

data(nhanes)

#Check count and percentage missing.
nhanes %>%
  inspect_na()

#Check missingness pattern. 
md.pattern(nhanes)

#Make a regression model predicting age from bmi. 
fit <- with(nhanes, lm(age ~ bmi))
summary(fit)

#Impute the missing nhanes data with mean substitution. 
imp <- mice(nhanes, 
            method = "mean", 
            m = 1, #1 imputation per missing datum. 
            maxit = 1) #1 algorithmic iteration.

#View the completed dataset. 
complete

#Confirm the numbers you see in the previosuly NA columns are actually means. 
colMeans(nhanes, na.rm = T)

#Update the regression model with the new data. 
fit <- with(imp, lm(age ~ bmi))
summary(fit)

#Impute the missing nhanes data with regression.
imp <- mice(nhanes, 
            method = "norm.predict",
            m = 1,
            maxit = 1)

#Inspect completed data. 
complete(imp)

#Inspect regression model with imputed data. 
fit <- with(imp, lm(age ~ bmi))
summary(fit)

#Impute the missing data with stochastic regression.
imp <- mice(nhanes, 
            method = "norm.nob", 
            m = 1, 
            maxi = 1)
complete(imp)
fit <- with(imp, lm(age~bmi))
summary(fit)

#Instead of telling mice what to do, let's allow mice to work its defaults.
imp <- mice(nhanes)
imp

#Check out all the different types of info stored in imp. 
attributes(imp)

#Look at all the original data, with the missing values...
imp$data
#... and at the imputed data.
imp$imp

#Look at the completed dataset, using the third imputed dataset out of teh five generated by default. 
c3 <- complete(imp,
               m = 3) #The 3rd dataset of 5 generated. 

#Pull the entire collection of imputed datasets.
complete(imp, "long")
complete(imp, "broad")

#Change the predictor matrix.
imp <- mice(nhanes, 
            m = 3, #3 imputed datasets 
            set.seed = 123,
            print = F) #Don't print the iteration cycle
imp$predictorMatrix 
#A value of 1 indicates that the column was used to impute the row.
#A value of 0 indicates that the column was not used to impute the row. 
#The diagonal is 0 bc variables cannot be used to impute themselves. 

#Get the initial predictor matrix, before imputation.
ini <- mice(nhanes, 
            maxit = 0, #Before any iterations were completed. 
            print = F)
pred <- ini$predictorMatrix
pred

#Remove the variable "hyp" from predictors, but allow it to be predicted. 
pred[, "hyp"] <- 0
pred

#Inspect the algorithmic convergence. 
plot(imp)
#The plots should look pretty random. 

#Check out all the possible different imputation methods.
methods(mice)

#Change the imputation method for a specific variable. 
data("nhanes2")
imp <- mice(nhanes2, print = F)
imp$method
#Change bmi from pmm to norm (Bayesian linear regression)
ini <- mice(nhanes2, maxit = 0)
meth <- ini$method
meth["bmi"] <- "norm"
#Run the imputations again and check the plots.
imp <- mice(nhanes2, 
            method = meth, #Specify to use the updated methods
            print = F)
complete(imp)
plot(imp)

#Extend the number of iterations past the default 5.
imp40 <- mice.mids(imp, #mice.mids takes the base mice and adds to it. 
                   maxit = 35, 
                   print = F)
plot(imp40)

#Compare the imputations against the observed values. 
#Observed: Blue. Imputed: Red.
stripplot(imp, 
          chl ~ .imp, #Focus on chl in imp
          pch = 20, #Shape 
          cex = 2) #Size

#Build a model predicting bmi from chl.
fit <- with(imp, lm(bmi ~ chl))
fit #You'll get regression outputs for all 5 iterations. 

#Check out all the cool things available in the new fit object. 
ls(fit)

#Observe the entire summary of the 2nd regression model.
summary(fit$analyses[[2]])

#Pool (combine) everything together.
pool.fit <- pool(fit)
summary(pool.fit)

#Review missingness. 
data(boys)
mpat <- md.pattern(boys)
mpat
#The far right variables are missing the most. 
#The far left number is the total number of complete cases. 
#The second row says there are 19 cases in which 1 variable (tv) is missing. 
sum(mpat[, "gen"] == 0)
#The gen column says that there are 8 (pink) patterns of missingness, and 503 total cases. 

#Does the missing data in one variable depend on another?
#See if missing gen depends on age. Make dummy variable for missing gen...
boys <- boys %>%
  mutate(gen_missing = ifelse(is.na(gen), TRUE, FALSE))
#... then see if the missing gen values are distributed evenly across ages.  
boys %>%
  ggplot(aes(x = age)) + 
  geom_histogram(binwidth = 3, color = "black", fill = "white") +
  facet_wrap(~gen_missing)
#Not an even distribution, so missing gen does not depend on age. 

#Impute missing data in boys. 
imp1 <- mice(boys, print = F)

#Compare the results of the original data with the imputed data. 
summary(boys)
summary(complete(imp1))

#Get a summary for a specific imputed variable. 
summary(with(imp1, mean(tv)))


#Impute missing data from mammalsleep with 10 algorithmic iterations.  
imp <- mice(mammalsleep, 
            maxit = 10,
            print = F)
#Build a model with the imputed data predicting sws from bw and odi.  
fit1 <- with(imp, lm(sws ~ log10(bw) + odi), print = F)
#Pool and inspect.
x <- pool(fit1)
x$lambda

#fmi (fraction of missing info due to nonresponse) and lambda (variance due to nonresponse) are very high. 
#If lambda and fmi are too high, you prolly included a crazy categorical variable. 

#Run imputation again but exlclude species. 
impnew <- mice(mammalsleep[, -1], #Remove the first column (species) 
               maxit = 10,
               print = F)
fit2 <- with(impnew, lm(sws ~ log10(bw) + odi))
y <- pool(fit2)

#Call the pools right next to eachother. 
x
y
#fmi and lambda decreased alot, indicating that the imputation model is a better fit.
plot(impnew)
#However, the models are highly converged. 


#Vignette 4: Passive imputation and post-processing. https://www.gerkovink.com/miceVignettes/Passive_Post_processing/Passive_imputation_post_processing.html

#Use passive imputation to impute a relationship.

ini <- mice(mammalsleep[,-1], maxit = 0, print = F)
#Check out all the default imputation methods.
meth <- ini$method
#Tell ts to use a compositional relationship as it's imputation method.  
meth["ts"] <- "~I(sws + ps)"
#Check out the defualt predictor matrix.
pred <- ini$predictorMatrix
#Tell ts to not serve as a predictor for sws and ps in the imputation model.  
pred[c("sws", "ps"), "ts"] <- 0
#Impute values with custom predictor matrix and method vector.
pas.imp <- mice(mammalsleep[,-1], #Use all vars except for the first column 
                method = meth, #Use the custom method vector
                predictorMatrix = pred, #Use the custom predictor matrix
                maxit = 10,
                seed = 123,
                print = F)
plot(pas.imp)

#Post-processing. AKA Constrain the values of a cetain variable that are used as predictors.
ini <- mice(boys, maxit = 0)
meth <- ini$method
#Make a custom method vector.
meth["tv"] <- "norm"
post <- ini$post
#Constrain the values of tv.
post["tv"] <- "imp[[j]][,i] <- squeeze(imp[[j]][,i], c(1,25))"
imp <- mice(boys, 
            method = meth, #Use the custome method vector
            post = post, #Use the constrained values of tv
            print = F)

#Compare the default solution to the post-processed (constrained) solution. 
#Make imputed model for the initial data.
imp.pmm <- mice(boys, print = F)
#Compare values. 
table(complete(imp)$tv)
table(complete(imp.pmm)$tv)
#Compare density plots. Red is imputed, blue is observed. 
densityplot(imp, ~tv)
#Compare density plots between the two methods.
#First, create a combnined df. 
tv <- c(complete(imp.pmm)$tv, complete(imp)$tv)
method <- rep(c("pmm", "norm"), each = nrow(boys))
tvm <- data.frame(tv = tv, method = method)
#Then plot the new dataframe (tvm).
ggplot(tvm, aes(x = tv)) +
  geom_histogram(binwidth = 1, color = "black", fill = "cadetblue")

# Vignette 5: Imputing multilevel data. https://www.gerkovink.com/miceVignettes/Multi_level/Multi_level_data.html
library(lattice)
library(tidyverse)
library(pan)
library(mice)
#DOwnload: https://github.com/gerkovink/miceVignettes/blob/master/Multi_level/popular.RData
load("C:\\Users\\Nbroussard\\Desktop\\popular.RData")

#Does the missing data in popular depend on popteach? 
#Create a histogram asking for the distribution of popteach given missingness in popular.
histogram(~popteach | is.na(popular), data = popNCR)

#Does the missingness in popteach influence other variables?
histogram(~popteach | is.na(sex), data = popNCR)

#Compute the intraclass correlation coefficient (icc) between class and popular/popteahc/texp. ICC is the correlation coefficient for groups rather than pairs (which is the traditional correlation method)
library(multilevel) #icc()
icc(aov(popular ~ class, data = popNCR))
icc(aov(popteach ~ class, data = popNCR))
icc(aov(texp ~ class, data = popNCR))

#Impute popNCR.
#First, replace method for extrav, texp, popular and popteach from pmm to norm.
ini <- mice(popNCR, maxit = 0)
meth <- ini$method
meth[c(3,5,6,7)] <- "norm"
#Then, exclude class and pupil as predictors for all variables. 
pred <- ini$predictorMatrix
pred[, "class"] <- 0
pred[, "pupil"] <- 0
#And finally, impute. 
imp1 <- mice(popNCR, method = meth, predictorMatrix = pred, print = F)

#Compare means in the original df and the imputed df. 
summary(complete(imp1))
summary(popNCR)
#If there isnt alot a diff between the two dfs, then the missing data is MAR. If there's a big diff, then the data is MNAR. If the imputed data means are higher, then there is alot of missing data at th ehigher end. If the imputed means are lower, then there is alot of missing data at the low end.   

#Compare ICCs. 
data.frame(vars = names(popNCR[c(6, 7, 5)]), 
           observed = c(icc(aov(popular ~ class, popNCR)), 
                        icc(aov(popteach ~ class, popNCR)), 
                        icc(aov(texp ~ class, popNCR))), 
           norm     = c(icc(aov(popular ~ class, complete(imp1))), 
                        icc(aov(popteach ~ class, complete(imp1))), 
                        icc(aov(texp ~ class, complete(imp1)))))

ini <- mice(popNCR, maxit = 0)
meth <- ini$method
pred <- ini$predictorMatrix
pred[, "pupil"] <- 0
imp2 <- mice(popNCR, method = meth, predictorMatrix = pred, print = F)


#Vignette 6: Sensitivity analysis https://www.gerkovink.com/miceVignettes/Sensitivity_analysis/Sensitivity_analysis.html
library(mice)
library(tidyverse)
library(lattice)
library(survival)

